name: Coverage of Test Build

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    name: "Generate coverage report for tests"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: 'true'
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest hypothesis pandas coverage cython

      - name: Generate cython
        run: |
          chmod +x ./tools/generate_cython.sh
          ./tools/generate_cython.sh

      # for cython tests inplace installation is required
      - name: build
        run: CXXFLAGS=-DCYTHON_TRACE_NOGIL=1 pip install -e . -v

      - name: Test with pytest and generate coverage info
        run: |
          PYTHONPATH=$(pwd)/src coverage run -m pytest tests
          coverage xml
          coverage report

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
